// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfpxeuyliwhjpegcydps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmcHhldXlsaXdoanBlZ2N5ZHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTA0MjYsImV4cCI6MjA1OTc4NjQyNn0.5uwfwwdhxOQh3uZ0Rj8mIdw6xYPHeccCxfimYhu08ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);